apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: container-1
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      - name: container-2
        image: redis:3.2
        ports:
        - containerPort: 6379
        